version: '2'

services:
  zoo1:
    image: zookeeper
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./zk-multiple-kafka-multiple/zoo1/data:/data
      - ./zk-multiple-kafka-multiple/zoo1/datalog:/datalog
    networks:
      kakfaatest-network:
        ipv4_address: 182.19.0.100

  zoo2:
    image: zookeeper
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./zk-multiple-kafka-multiple/zoo2/data:/data
      - ./zk-multiple-kafka-multiple/zoo2/datalog:/datalog
    networks:
      kakfaatest-network:
        ipv4_address: 182.19.0.101

  zoo3:
    image: zookeeper
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - ./zk-multiple-kafka-multiple/zoo3/data:/data
      - ./zk-multiple-kafka-multiple/zoo3/datalog:/datalog
    networks:
      kakfaatest-network:
        ipv4_address: 182.19.0.102

  kafka1:
    image: wurstmeister/kafka
    ports:
      - "3003:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://182.19.0.103:9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    volumes:
      - ./zk-multiple-kafka-multiple/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      kakfaatest-network:
        ipv4_address: 182.19.0.103

  kafka2:
    image: wurstmeister/kafka
    ports:
      - "3004:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://182.19.0.104:9092
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    volumes:
      - ./zk-multiple-kafka-multiple/kafka2/data:/var/lib/kafka/data
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      kakfaatest-network:
        ipv4_address: 182.19.0.104

  kafka3:
    image: wurstmeister/kafka
    ports:
      - "3005:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://182.19.0.105:9092
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    volumes:
      - ./zk-multiple-kafka-multiple/kafka3/data:/var/lib/kafka/data
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      kakfaatest-network:
        ipv4_address: 182.19.0.105

networks:
  kakfaatest-network:
    driver: bridge
    ipam:
      config:
        - subnet: 182.19.0.0/21
          gateway: 182.19.0.1